from card import Card, Rarity

cards = [
    Card("Skeletons", Rarity.COMMON),
    Card("Ice Spirit", Rarity.COMMON),
    Card("Fire Spirit", Rarity.COMMON),
    Card("Electro Spirit", Rarity.COMMON),
    Card("Goblins", Rarity.COMMON),
    Card("Bomber", Rarity.COMMON),
    Card("Spear Goblins", Rarity.COMMON),
    Card("Bats", Rarity.COMMON),
    Card("Berserker", Rarity.COMMON),
    Card("Zap", Rarity.COMMON),
    Card("Giant Snowball", Rarity.COMMON),
    Card("Knight", Rarity.COMMON),
    Card("Archers", Rarity.COMMON),
    Card("Minions", Rarity.COMMON),
    Card("Goblin Gang", Rarity.COMMON),
    Card("Skeleton Barrel", Rarity.COMMON),
    Card("Firecracker", Rarity.COMMON),
    Card("Cannon", Rarity.COMMON),
    Card("Arrows", Rarity.COMMON),
    Card("Royal Delivery", Rarity.COMMON),
    Card("Skeleton Dragons", Rarity.COMMON),
    Card("Mortar", Rarity.COMMON),
    Card("Tesla", Rarity.COMMON),
    Card("Barbarians", Rarity.COMMON),
    Card("Minion Horde", Rarity.COMMON),
    Card("Rascals", Rarity.COMMON),
    Card("Royal Giant", Rarity.COMMON),
    Card("Elite Barbarians", Rarity.COMMON),
    Card("Royal Recruits", Rarity.COMMON),

    Card("Heal Spirit", Rarity.RARE),
    Card("Ice Golem", Rarity.RARE),
    Card("Suspicious Bush", Rarity.RARE),
    Card("Mega Minion", Rarity.RARE),
    Card("Dart Goblin", Rarity.RARE),
    Card("Elixir Golem", Rarity.RARE),
    Card("Tombstone", Rarity.RARE),
    Card("Earthquake", Rarity.RARE),
    Card("Valkyrie", Rarity.RARE),
    Card("Musketeer", Rarity.RARE),
    Card("Mini PEKKA", Rarity.RARE),
    Card("Hog Rider", Rarity.RARE),
    Card("Battle Ram", Rarity.RARE),
    Card("Zappies", Rarity.RARE),
    Card("Flying Machine", Rarity.RARE),
    Card("Battle Healer", Rarity.RARE),
    Card("Goblin Demolisher", Rarity.RARE),
    Card("Goblin Hut", Rarity.RARE),
    Card("Bomb Tower", Rarity.RARE),
    Card("Furnace", Rarity.RARE),
    Card("Goblin Cage", Rarity.RARE),
    Card("Fireball", Rarity.RARE),
    Card("Giant", Rarity.RARE),
    Card("Wizard", Rarity.RARE),
    Card("Royal Hogs", Rarity.RARE),
    Card("Inferno Tower", Rarity.RARE),
    Card("Barbarian Hut", Rarity.RARE),
    Card("Elixir Collector", Rarity.RARE),
    Card("Rocket", Rarity.RARE),
    Card("Three Musketeers", Rarity.RARE),

    Card("Mirror", Rarity.EPIC),
    Card("Wall Breakers", Rarity.EPIC),
    Card("Rage", Rarity.EPIC),
    Card("Barbarian Barrel", Rarity.EPIC),
    Card("Goblin Curse", Rarity.EPIC),
    Card("Skeleton Army", Rarity.EPIC),
    Card("Guards", Rarity.EPIC),
    Card("Goblin Barrel", Rarity.EPIC),
    Card("Tornado", Rarity.EPIC),
    Card("Clone", Rarity.EPIC),
    Card("Void", Rarity.EPIC),
    Card("Vines", Rarity.EPIC),
    Card("Baby Dragon", Rarity.EPIC),
    Card("Dark Prince", Rarity.EPIC),
    Card("Hunter", Rarity.EPIC),
    Card("Rune Giant", Rarity.EPIC),
    Card("Goblin Drill", Rarity.EPIC),
    Card("Freeze", Rarity.EPIC),
    Card("Poison", Rarity.EPIC),
    Card("Balloon", Rarity.EPIC),
    Card("Witch", Rarity.EPIC),
    Card("Prince", Rarity.EPIC),
    Card("Bowler", Rarity.EPIC),
    Card("Executioner", Rarity.EPIC),
    Card("Cannon Cart", Rarity.EPIC),
    Card("Electro Dragon", Rarity.EPIC),
    Card("Giant Skeleton", Rarity.EPIC),
    Card("Goblin Giant", Rarity.EPIC),
    Card("X-Bow", Rarity.EPIC),
    Card("Lightning", Rarity.EPIC),
    Card("PEKKA", Rarity.EPIC),
    Card("Electro Giant", Rarity.EPIC),
    Card("Golem", Rarity.EPIC),

    Card("The Log", Rarity.LEGENDARY),
    Card("Ice Wizard", Rarity.LEGENDARY),
    Card("Princess", Rarity.LEGENDARY),
    Card("Miner", Rarity.LEGENDARY),
    Card("Bandit", Rarity.LEGENDARY),
    Card("Royal Ghost", Rarity.LEGENDARY),
    Card("Fisherman", Rarity.LEGENDARY),
    Card("Lumberjack", Rarity.LEGENDARY),
    Card("Inferno Dragon", Rarity.LEGENDARY),
    Card("Electro Wizard", Rarity.LEGENDARY),
    Card("Night Witch", Rarity.LEGENDARY),
    Card("Magic Archer", Rarity.LEGENDARY),
    Card("Mother Witch", Rarity.LEGENDARY),
    Card("Phoenix", Rarity.LEGENDARY),
    Card("Ram Rider", Rarity.LEGENDARY),
    Card("Goblin Machine", Rarity.LEGENDARY),
    Card("Graveyard", Rarity.LEGENDARY),
    Card("Sparky", Rarity.LEGENDARY),
    Card("Spirit Empress", Rarity.LEGENDARY),
    Card("Lava Hound", Rarity.LEGENDARY),
    Card("Mega Knight", Rarity.LEGENDARY),
    Card("Ronin", Rarity.LEGENDARY),

    Card("Little Prince", Rarity.CHAMPION),
    Card("Mighty Miner", Rarity.CHAMPION),
    Card("Skeleton King", Rarity.CHAMPION),
    Card("Golden Knight", Rarity.CHAMPION),
    Card("Archer Queen", Rarity.CHAMPION),
    Card("Monk", Rarity.CHAMPION),
    Card("Goblinstein", Rarity.CHAMPION),
    Card("Boss Bandit", Rarity.CHAMPION),
]
